<form action="<?= $block->getUrl('custom_formfetchplugin/customer/submit') ?>" method="post">
    <fieldset>
        <legend>Custom Form</legend>
        <label for="email">Email:</label>
        <input type="email" name="email" id="email" required />

        <label for="first_name">First Name:</label>
        <input type="text" name="first_name" id="first_name" required />

        <label for="last_name">Last Name:</label>
        <input type="text" name="last_name" id="last_name" required />

        <label for="school_name">School Name:</label>
        <input type="text" name="school_name" id="school_name" required />

        <button type="submit">Submit</button>
    </fieldset>
</form>
